import { ENV_CONFIG } from './env.config';

const API_VERSION = ENV_CONFIG.API_VERSION || 'v1';
const BASE_PATH = `${ENV_CONFIG.PROXY_BASE_URL}/gateway/${API_VERSION}`;

export const API_ROUTES = {
  AUTH: {
    SIGNUP: `${BASE_PATH}/auth/signup`,
    SIGNIN: `${BASE_PATH}/auth/signin`,
    SIGNOUT: `${BASE_PATH}/auth/signout`,
    ACTIVATE_ACCOUNT: `${BASE_PATH}/auth/activate-account`,
    REFRESH_TOKEN: `${BASE_PATH}/auth/refresh-token`,
    FORGOT_PASSWORD: `${BASE_PATH}/auth/forgot-password`,
    RESET_PASSWORD: `${BASE_PATH}/auth/reset-password`,
    CHANGE_PASSWORD: `${BASE_PATH}/auth/change-password`,
    RESEND_ACTIVATION: `${BASE_PATH}/auth/resend-activation`,
    SETUP_PIN: `${BASE_PATH}/auth/setup-pin`,
    VERIFY_PIN: `${BASE_PATH}/auth/verify-pin`,
    PIN_STATUS: `${BASE_PATH}/auth/pin-status`,
  },
  REQUEST: {
    INVENTORY_SPARE_PART: `${BASE_PATH}/request/inventory-spare-part-request`,
    NON_INVENTORY_SPARE_PART: `${BASE_PATH}/request/non-inventory-spare-part-request`,
    ASSIGN_TO_SELLER: `${BASE_PATH}/request/assign-request-to-seller`,
    DETAIL: `${BASE_PATH}/request/request-datail`, // backend typo kept intentionally
    BUYER_ACTIVE_ALL: `${BASE_PATH}/request/buyer-active-request-all`,
    BUYER_HISTORY_ALL: `${BASE_PATH}/request/buyer-request-history-all`,
    GOPA_SELLER_FOR_REQUEST: `${BASE_PATH}/request/GOPA-seller-for-request`,
    GOPA_ASSIGNED_ACTIVE: `${BASE_PATH}/request/GOPA-assigned-active-request`,
    GOPA_ASSIGNED_HISTORY: `${BASE_PATH}/request/GOPA-assigned-request-history`,
    GOPA_UNASSIGNED_ACTIVE: `${BASE_PATH}/request/GOPA-unassigned-active-request`,
    GOPA_UNASSIGNED_HISTORY: `${BASE_PATH}/request/GOPA-unassigned-request-history`,
  },
  BID: {
    SUBMIT: `${BASE_PATH}/bid/submit-bid`,
    UPLOAD_IMAGES: `${BASE_PATH}/bid/upload-sparepart-images`,
    REQUEST_BIDS_ALL: `${BASE_PATH}/bid/request-bids-all`,
    BIDS_FOR_BUYER_ALL: `${BASE_PATH}/bid/bids-for-buyer-request-all`,
    SELLER_ACTIVE_ALL: `${BASE_PATH}/bid/seller-bids-for-active-requests-all`,
    SELLER_HISTORY_ALL: `${BASE_PATH}/bid/seller-bids-for-requests-history-all`,
  },
  CART: {
    ADD_BID: `${BASE_PATH}/cart/add-bid-to-cart`,
    REMOVE_BID: `${BASE_PATH}/cart/remove-bid-from-cart`,
    ITEMS_ALL: `${BASE_PATH}/cart/items-in-cart-all`,
  },
  CHECKOUT: {
    WITH_EXISTING_ADDRESS: `${BASE_PATH}/checkout/with-existing-address`,
    WITH_NEW_ADDRESS: `${BASE_PATH}/checkout/with-new-address`,
  },
  INVOICE: {
    ACCEPT_BY_GOPA: `${BASE_PATH}/invoice/accept-invoice-by-gopa`,
    FOR_GOPA_TO_ACCEPT: `${BASE_PATH}/invoice/get-invoice-for-gopa-to-accept`,
    GOPA_ACCEPTED: `${BASE_PATH}/invoice/get-gopa-accepted-invoice`,
    DETAILS: `${BASE_PATH}/invoice/get-invoice-details`,
    ITEM_DETAILS: `${BASE_PATH}/invoice/get-invoice-item-details`,
    MY_PENDING: `${BASE_PATH}/invoice/get-my-pending-invoices`,
    MY_HISTORY: `${BASE_PATH}/invoice/get-my-history-invoices`,
    SELLER_PENDING: `${BASE_PATH}/invoice/get-seller-pending-invoices`,
    SELLER_HISTORY: `${BASE_PATH}/invoice/get-seller-history-invoices`,
    SET_READY_FOR_PICKUP: `${BASE_PATH}/invoice/set-orderitem-ready-for-pickup`,
    ACCEPT_PICKUP: `${BASE_PATH}/invoice/accept-orderitem-pickup`,
    SELLER_DELIVER_TO_RIDER: `${BASE_PATH}/invoice/seller-deliver-orderitem-to-rider`,
    PENDING_RIDER_ACCEPTANCE: `${BASE_PATH}/invoice/get-invoice-pending-rider-acceptance`,
    PENDING_RIDER_PICKUP: `${BASE_PATH}/invoice/get-invoice-pending-rider-pickup`,
    ITEM_BY_QR: `${BASE_PATH}/invoice/get-invoice-item-by-qr`,
    READY_TO_SHIP_ITEMS: `${BASE_PATH}/invoice/get-readytoship-invoice-items`,
    SET_READY_FOR_SHIPMENT: `${BASE_PATH}/invoice/set-item-ready-for-shipment`,
    DELIVER_TO_BUYER: `${BASE_PATH}/invoice/deliver-item-to-buyer`,
  },
  CHARGE: {
    GET_USER_CHARGES: `${BASE_PATH}/charge/get-user-charges`,
  },
  WALLET: {
    MY_DETAILS: `${BASE_PATH}/wallet/get-my-wallet-details`,
  },
  ADDRESS: {
    ADD: `${BASE_PATH}/address/add-address`,
    MY_ADDRESSES: `${BASE_PATH}/address/get-my-addresses`,
    DETAILS_BY_ID: `${BASE_PATH}/address/get-details-by-id`,
  },
  OTP: {
    GENERATE: `${BASE_PATH}/otp/generate`,
    VALIDATE: `${BASE_PATH}/otp/validate`,
  },
  INVENTORY: {
    CAR_MANUFACTURERS_ALL: `${BASE_PATH}/inventry/car-manufacturers-all`,
    CAR_BRANDS_ALL: `${BASE_PATH}/inventry/car-brands-all`,
    CAR_MODELS_ALL: `${BASE_PATH}/inventry/car-models-all`,
    SPAREPART_ALL: `${BASE_PATH}/inventry/sparepart-all`,
    SPAREPART_DETAIL: `${BASE_PATH}/inventry/sparepart-detail`,
    CATEGORY_ALL: `${BASE_PATH}/inventry/category-all`,
  },
  USER: {
    ADD_IDENTIFICATION_SELF: `${BASE_PATH}/user/add-identification-self`,
    GOPA_REGISTRATION_SELF: `${BASE_PATH}/user/gopa-registration-self`,
    SELLER_REGISTRATION_SELF: `${BASE_PATH}/user/seller-registration-self`,
    MEPA_REGISTRATION_SELF: `${BASE_PATH}/user/mepa-registration-self`,
    RIDER_REGISTRATION_SELF: `${BASE_PATH}/user/rider-registration-self`,
    RIDER_VEHICLE_REGISTRATION_SELF: `${BASE_PATH}/user/rider-vehicle-registration-self`,
    PAYMENT_ACCOUNT_SELF: `${BASE_PATH}/user/payment-account-creation-self`,
    UPLOAD_SELLER_DOC: `${BASE_PATH}/user/upload-seller-doc`,
    UPLOAD_RIDER_LICENSE_FRONT: `${BASE_PATH}/user/upload-rider-license-front`,
    UPLOAD_RIDER_LICENSE_BACK: `${BASE_PATH}/user/upload-rider-license-back`,
    UPLOAD_RIDER_VEHICLE_FRONT: `${BASE_PATH}/user/upload-rider-vehicle-front`,
    RIDER_VEHICLES_SELF: `${BASE_PATH}/user/rider-vehicles-self`,
    IDENTIFICATION_SELF: `${BASE_PATH}/user/user-identification-self`,
    DETAILS: `${BASE_PATH}/user/user-details`,
  },
  ADVERT: {
    SLIDER_ACTIVE: `${BASE_PATH}/advert/slider-active`,
  },
  CHAT: {
    RB: {
      SEND_MESSAGE: `${BASE_PATH}/chat/rb/send-message`,
      MARK_READ: `${BASE_PATH}/chat/rb/mark-message-as-read`,
      MARK_MULTIPLE_READ: `${BASE_PATH}/chat/rb/mark-multiple-message-as-read`,
      CONVERSATION: `${BASE_PATH}/chat/rb/conversation`,
      CONVERSATION_LIST: `${BASE_PATH}/chat/rb/conversation-list`,
      MESSAGES: `${BASE_PATH}/chat/rb/messages`,
      CONVERSATION_MESSAGES: `${BASE_PATH}/chat/rb/conversation-messages`,
    },
    RS: {
      SEND_MESSAGE: `${BASE_PATH}/chat/rs/send-message`,
      MARK_READ: `${BASE_PATH}/chat/rs/mark-message-as-read`,
      MARK_MULTIPLE_READ: `${BASE_PATH}/chat/rs/mark-multiple-message-as-read`,
      CONVERSATION: `${BASE_PATH}/chat/rs/conversation`,
      CONVERSATION_LIST: `${BASE_PATH}/chat/rs/conversation-list`,
      MESSAGES: `${BASE_PATH}/chat/rs/messages`,
      CONVERSATION_MESSAGES: `${BASE_PATH}/chat/rs/conversation-messages`,
    },
    UC: {
      SEND_MESSAGE: `${BASE_PATH}/chat/uc/send-message`,
      MARK_READ: `${BASE_PATH}/chat/uc/mark-message-as-read`,
      MARK_MULTIPLE_READ: `${BASE_PATH}/chat/uc/mark-multiple-message-as-read`,
      CONVERSATION: `${BASE_PATH}/chat/uc/conversation`,
      CONVERSATION_LIST: `${BASE_PATH}/chat/uc/conversation-list`,
      MESSAGES: `${BASE_PATH}/chat/uc/messages`,
      CONVERSATION_MESSAGES: `${BASE_PATH}/chat/uc/conversation-messages`,
    },
  },
};
